import random
import string
randomtext = string.ascii_letters + string.digits + string.punctuation
num_cha = random.randint(15,32)
password = ''.join(random.sample(randomtext,num_cha))
password2 = ''.join(random.sample(randomtext,num_cha))
password3 = ''.join(random.sample(randomtext,num_cha))
password4 = ''.join(random.sample(randomtext,num_cha))
password5 = ''.join(random.sample(randomtext,num_cha))
password6 = ''.join(random.sample(randomtext,num_cha))
password7 = ''.join(random.sample(randomtext,num_cha))
password8 = ''.join(random.sample(randomtext,num_cha))
password9 = ''.join(random.sample(randomtext,num_cha))
password10 = ''.join(random.sample(randomtext,num_cha))
print(password)
print(password2)
print(password3)
print(password4)
print(password5)
print(password6)
print(password7)
print(password8)
print(password9)
print(password10)
